### ISSUE TITLE
Obfs4 Connection to OpenVPN Failed

### ISSUE THREAD

**Issue by yamuk** [OpenInternet/PT-website#18]
I've been testing Shapeshifter-dispatcher with OpenVPN using obfs2 on a Ubuntu 16.04 server for a couple of months now. It works really good but obfs2 can be passively blocked easily. So I try to set it up with obfs4 following the latest instruction:   
[https://github.com/OperatorFoundation/shapeshifter-dispatcher/blob/master/README.md](url)

Unfortunately the connection fails, probably on the client side. Also it's unable to generate any log file so I'm unable to check what went wrong.

Followings are the command lines I use that launch the client and server successfully.

Server :
bin/shapeshifter-dispatcher --server --transparent --ptversion 2 --state state --orport 127.0.0.1:1194 --transports obfs4 --bindaddr obfs4- MyServerIP:2222 --logLevel DEBUG --enableLogging 

Client:
-client -transparent -ptversion 2 -state state -target MyServerIP:2222 -transports obfs4 -bindaddr obfs4-127.0.0.1:1194 -options '{"cert": "CMYgNUg4IUb9tZmF9D3RbKH6cT1w07lAqocuhIN7tzxWiAdgvdqMq4d6BftKf5eRtM8OBg", "iatMode": "0"}' -logLevel DEBUG -enableLogging

Connection initiated by OpenVPN:
remote 127.0.0.1
port 1234

This is the log of OpenVPN client:

Mon Aug 07 16:43:45 2017 OpenVPN 2.4.0 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Jan 31 2017
Mon Aug 07 16:43:45 2017 Windows version 6.1 (Windows 7) 64bit
Mon Aug 07 16:43:45 2017 library versions: OpenSSL 1.0.2k  26 Jan 2017, LZO 2.09
Enter Management Password:
Mon Aug 07 16:43:45 2017 MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:25340
Mon Aug 07 16:43:45 2017 Need hold release from management interface, waiting...
Mon Aug 07 16:43:45 2017 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:25340
Mon Aug 07 16:43:45 2017 MANAGEMENT: CMD 'state on'
Mon Aug 07 16:43:45 2017 MANAGEMENT: CMD 'log all on'
Mon Aug 07 16:43:45 2017 MANAGEMENT: CMD 'hold off'
Mon Aug 07 16:43:45 2017 MANAGEMENT: CMD 'hold release'
Mon Aug 07 16:43:45 2017 Outgoing Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
Mon Aug 07 16:43:45 2017 Incoming Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
Mon Aug 07 16:43:45 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]127.0.0.1:1234
Mon Aug 07 16:43:45 2017 Socket Buffers: R=[8192->8192] S=[8192->8192]
Mon Aug 07 16:43:45 2017 Attempting to establish TCP connection with [AF_INET]127.0.0.1:1234 [nonblock]
Mon Aug 07 16:43:45 2017 MANAGEMENT: >STATE:1502120625,TCP_CONNECT,,,,,,
Mon Aug 07 16:43:45 2017 TCP connection established with [AF_INET]127.0.0.1:1234
Mon Aug 07 16:43:45 2017 TCP_CLIENT link local: (not bound)
Mon Aug 07 16:43:45 2017 TCP_CLIENT link remote: [AF_INET]127.0.0.1:1234
Mon Aug 07 16:43:45 2017 MANAGEMENT: >STATE:1502120625,WAIT,,,,,,
Mon Aug 07 16:43:45 2017 Connection reset, restarting [-1]
Mon Aug 07 16:43:45 2017 SIGUSR1[soft,connection-reset] received, process restarting
Mon Aug 07 16:43:45 2017 MANAGEMENT: >STATE:1502120625,RECONNECTING,connection-reset,,,,,
Mon Aug 07 16:43:45 2017 Restart pause, 5 second(s)
Mon Aug 07 16:43:50 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]127.0.0.1:1234
Mon Aug 07 16:43:50 2017 Socket Buffers: R=[8192->8192] S=[8192->8192]
Mon Aug 07 16:43:50 2017 Attempting to establish TCP connection with [AF_INET]127.0.0.1:1234 [nonblock]
Mon Aug 07 16:43:50 2017 MANAGEMENT: >STATE:1502120630,TCP_CONNECT,,,,,,
Mon Aug 07 16:43:54 2017 SIGTERM[hard,init_instance] received, process exiting
Mon Aug 07 16:43:54 2017 MANAGEMENT: >STATE:1502120634,EXITING,init_instance,,,,,

What have I done wrong or anything I've missed? Thank you for any help.

**Comment by dlshad** [comment]
Hi @yamuk , did you generate obfs4 certificate by running this command first:
`bin/shapeshifter-dispatcher -transparent -server -state state -orport 127.0.0.1:3333 -transports obfs4 -bindaddr obfs4-127.0.0.1:2222 -logLevel DEBUG -enableLogging -extorport 127.0.0.1:3334
`
is the cert you're using in your example command generate by the previous step?
IF you can't see anything in the debug log file, that means obfs4 client-server are not connected. 
Also I see you are using windows on the client side, can you share more info on the OS, libraries used ..etc on both sides so I can replicate what you have and go through the steps.

**Comment by yamuk** [comment]
The cert was generated by running this command:
bin/shapeshifter-dispatcher --server --transparent --ptversion 2 --state state --orport 127.0.0.1:1194 --transports obfs4 --bindaddr obfs4- MyServerIP:2222 --logLevel DEBUG --enableLogging
All certs generated by previous steps were deleted to ensure I'm using the most updated one.  I did try to use the cert generated by:
bin/shapeshifter-dispatcher -transparent -server -state state -orport 127.0.0.1:3333 -transports obfs4 -bindaddr obfs4-127.0.0.1:2222 -logLevel DEBUG -enableLogging -extorport 127.0.0.1:3334
But it didn't work too.
The OS on the client side is Windows 7 Professional 64bit. The libraries used on both client and server are the standard libraries given by the golang installation. Obfs2 works perfectly on the same setup. Just when I switched to Obfs4 I had this issue.

**Comment by dlshad** [comment]
Hi again Yamuk,
I just replicated what you got and I got it to work, 
here are my notes,
Server:
- On the server side, make sure that port 2222 is open to the public
- Remove the space between obfs4- and MyServerIP:2222 and make it obfs4-MyServerIP:2222
- Make sure that MyServerIP = You server public's IP address 
Here is what I used on the server as a command:

bin/shapeshifter-dispatcher -transparent -server -state state -orport 127.0.0.1:443 -transports obfs4 -bindaddr obfs4-138.68.xxx.xxx:2222 -logLevel DEBUG -enableLogging -extorport 127.0.0.1:3334

Where 443 is the port of my OpenVPN Server
138.68.xxx.xxx = my Server's public ip address

On the client: 
bin/shapeshifter-dispatcher -transparent -client -state state -target 138.68.xxx.xxx:2222  -transports obfs4 -bindaddr obfs4-127.0.0.1:443 -options '{"cert": "26sMRtp9OlJgdOsGpr741PHsk48QUVheINmi5R7oObfxghkrcbjuvQ3q9e/PATkvmMZJWQ", "iatMode": "0"}' -logLevel DEBUG -enableLogging

Make sure the ports 443 and 2222 are allowed.
Try the commands I posted and let me know.
Thanks again for sharing the issue with us. 
Dlshad

**Comment by dlshad** [comment]
Just an updated, in my previous comment, I replicated your setup but using Linux client. I tried it with Windows and it crashes here:
launching
ptclientproxy <nil>
Listening  127.0.0.1:1234
launched
Accepted
handling...
Transport is obfs4 '{cert:

I will investigate the issue and update you.

**Comment by yamuk** [comment]
That is exactly what happened. I also crashed there. Awaiting your update. Thank you very much.

**Comment by dlshad** [comment]
Hi @yamuk , here is an update .
I talked to @blanu from @OperatorFoundation and he shared some updates and instructions helped getting Shapeshifter-Dispatcher/obfs4 to work on windows. 

Please apply the following instructions and kindly share the results with us:
1- Test with the latest shapeshifter-dispatcher, Operator Foundation pushed  new updates:
`go get -u github.com/OperatorFoundation/shapeshifter-dispatcher/shapeshifter-dispatcher
`
2- Here is the command I used on the server side (Ubuntu 16.04 - OpenVPN)
`bin/shapeshifter-dispatcher -transparent -server -state state -orport 127.0.0.1:443 -transports obfs4 -bindaddr obfs4-138.68.xxx.xxx:2222 -logLevel DEBUG -enableLogging -extorport 127.0.0.1:3334`
3- Copy the certificate from the auto generated file 'obfs4_bridgeline.txt' located in state folder

Where 443 is OpenVPN port
2222 is Shapeshifter-dispatcher port which is going to be listening publicly 

On the client side, 
1- Test with the latest shapeshifter-dispatcher, Operator Foundation pushed  new updates:
`go get -u github.com/OperatorFoundation/shapeshifter-dispatcher/shapeshifter-dispatcher
`
2- Run the following command 
`shapeshifter-dispatcher -transparent -client -state state -target 138.68.xxx.xxx:2222 -transports obfs4 -options "{\"cert\": \"26sMRtp9OlJgdOsGpr741PHsk48QUVheINmi5R7oOLL7hPb1gMfxvQ3q9e/keyehdjaksbh\", \"iatMode\": \"0\"}" -logLevel DEBUG -enableLogging
`
Change the Certificate with the one you have. 
Good luck! 

Dlshad

**Comment by yamuk** [comment]
Great. It works with windows now. I'll work with it for my project in the next few weeks. If I find any issue I'll let you know. Thank you.

**Comment by dlshad** [comment]
Awesome this is great to hear! and we would love to know more about your project if you like, here is my email dothman@internews.org if you need help.
